# Generated by Django 5.1.3 on 2025-03-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=16)),
                ('service_type', models.TextField(blank=True, choices=[('P', 'painter'), ('B', 'bartender'), ('B2', 'bouncer')])),
                ('cost_estimate', models.FloatField()),
                ('region', models.TextField(blank=True, choices=[('R1', 'region_1'), ('R2', 'region_2'), ('R3', 'region_3')])),
            ],
            options={
                'ordering': ['region'],
            },
        ),
    ]
