# Generated by Django 5.1.3 on 2025-03-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_provider',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
